import { Box, Button, Grid, Paper, Stack } from "@mui/material";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{ height: "100vh", p: 1 }}
        direction={{ xs: "column", md: "row" }}
      >
        <Grid item xs={5} md={4}>
          <Grid container spacing={2} sx={{ height: "100%" }}>
            {Array(16)
              .fill(0)
              .map((_, i) => (
                <Grid item xs={3} key={Math.random()}>
                  <Button
                    className="fib fi-br fis"
                    sx={{ width: "100%", height: "100%" }}
                  />
                </Grid>
              ))}
          </Grid>
        </Grid>

        <Grid item xs={2} md={4}>
          Hello, world (cup)!
        </Grid>

        <Grid item xs={5} md={4}>
          <Grid container spacing={2} sx={{ height: "100%" }}>
            {Array(16)
              .fill(0)
              .map((_, i) => (
                <Grid item xs={3} key={Math.random()}>
                  <Button
                    className="fib fi-br fis"
                    sx={{ width: "100%", height: "100%" }}
                  />
                </Grid>
              ))}
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
}
